#!/bin/bash

# Gather system information
USERNAME=$(whoami)
DATE_TIME=$(date)
HOSTNAME=$(hostname)
OS="$(source /etc/os-release && echo "$PRETTY_NAME")"
UPTIME=$(uptime -p)

# Gather hardware information
CPU=$(lscpu | grep "Model name" | cut -d ':' -f2 | xargs)
RAM=$(free -h | awk '/^Mem:/ {print $2}')
DISKS=$(lsblk -d -o MODEL,SIZE | tail -n +2)
VIDEO=$(lspci | grep -i "VGA" | cut -d ':' -f3 | xargs)

# Gather network information
FQDN=$(hostname -f)
HOST_ADDRESS=$(ip route get 1 | awk '{print $7; exit}')
GATEWAY_IP=$(ip route | awk '/default/ {print $3}')
DNS_SERVER=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}' | paste -sd ", ")

# Gather system status
LOGGED_IN_USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd ", ")
DISK_SPACE=$(df -h --output=target,avail | tail -n +2)
PROCESS_COUNT=$(ps aux --no-headers | wc -l)
LOAD_AVERAGES=$(uptime | awk -F'load average:' '{print $2}' | xargs)
LISTENING_PORTS=$(ss -tuln | awk 'NR>1 {print $5}' | cut -d ':' -f2 | sort -nu | paste -sd ", ")
UFW_STATUS=$(sudo ufw status | grep -q "active" && echo "enabled" || echo "disabled")

# Generate the report
echo "\nSystem Report generated by $USERNAME, $DATE_TIME\n"

echo "## System Information"
echo "Hostname: $HOSTNAME"
echo "OS: $OS"
echo "Uptime: $UPTIME"

echo "## Hardware Information"
echo "CPU: $CPU"
echo "RAM: $RAM"
echo "Disks:\n$DISKS"
echo "Video: $VIDEO"

echo "## Network Information"
echo "FQDN: $FQDN"
echo "Host Address: $HOST_ADDRESS"
echo "Gateway IP: $GATEWAY_IP"
echo "DNS Server: $DNS_SERVER"

echo "## System Status"
echo "Users Logged In: $LOGGED_IN_USERS"
echo "Disk Space:\n$DISK_SPACE"
echo "Process Count: $PROCESS_COUNT"
echo "Load Averages: $LOAD_AVERAGES"
echo "Listening Network Ports: $LISTENING_PORTS"
echo "UFW Status: $UFW_STATUS"

echo "\n"
